name: Deployment

on:
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  packages: write
  pages: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Packages
      run: npm install
      
    - name: Build page
      run: npm run build
        
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        # GitHub token
        # token: ${{ github.token }}
          token: ${{ secrets.GITHUB_TOKEN }}
        # Name of the artifact to deploy
          artifact_name: github-pages
